### ISSUE TITLE
FAILED: stochastic_spec103_mustSignalOnMethodsSequentially

### ISSUE THREAD

**Issue by viktorklang** [jroper/reactive-streams-servlet#1]
~~~java
java.lang.AssertionError: Failed in iteration 4 of 100. Expected completion signal after signalling 10 elements (signalled 1), yet did not receive it within 1000 ms
	at org.testng.Assert.fail(Assert.java:89)
	at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:169)
	at org.reactivestreams.tck.TestEnvironment$Latch.expectClose(TestEnvironment.java:841)
	at org.reactivestreams.tck.PublisherVerification$5$1.run(PublisherVerification.java:347)
	at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1138)
	at org.reactivestreams.tck.PublisherVerification$5.apply(PublisherVerification.java:258)
	at org.reactivestreams.tck.PublisherVerification$5.apply(PublisherVerification.java:255)
	at org.reactivestreams.tck.PublisherVerification.stochasticTest(PublisherVerification.java:1207)
	at org.reactivestreams.tck.PublisherVerification.stochastic_spec103_mustSignalOnMethodsSequentially(PublisherVerification.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:129)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:88)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
~~~

**Comment by jroper** [comment]
Yeah I've seen that a couple of times. I don't have time at the moment to look into it deeper. I think a first thing to do might be to replace Jetty with Tomcat and see if the same problem occurs. If it does, then we know it's the reactive streams code. If not, then it's possible that it's Jetty, but it doesn't rule out the reactive streams code.

The thing is, I'm not aware of a lot of places where Servlet 3.1 asynchronous IO is actually used, hence implementations may have hidden bugs, especially when it comes to that test which is likely to put pressure on race conditions that aren't usually exercised.

**Comment by jroper** [comment]
I've added Tomcat tests in #3. I wasn't able to reproduce it with Tomcat with around about 10 test runs.

**Comment by jroper** [comment]
So, I've now turned on detailed logging for that test, and guess what! In 3 test runs on travis I haven't been able to reproduce it, compared to being able to reproduce it 100% of the time on travis without the detailed logging on. I'll have to reduce the logging (perhaps not log timestamps will be a good start).

**Comment by jroper** [comment]
I managed to reproduce it consistently enough locally to debug it, by writing the request body on the client side at random intervals (literally inserting a `Thread.sleep(random.nextInt(10))` between each write). Issue raised here:

https://github.com/eclipse/jetty.project/issues/2006
